apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oynoi8fun-python 
  janus-idp.io/tekton: oynoi8fun-python
  backstage.io/kubernetes-id: oynoi8fun-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oynoi8fun-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml