apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: oynoi8fun-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:b9e036a6bac0283e03c0dcab1de2ac02a7292f35@sha256:827c2ee5c055d0e03390fb7ae3a405d73e414d370c257f4f2c6b54a03f1f4676
          name: container-image
