apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oynoi8fun-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oynoi8fun-python 
  name: oynoi8fun-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oynoi8fun-python 
